package controller;

public interface ControllerVisitor {
	
	void visitMoveDeckToDiscards(MoveDeckToDiscardsController moveDeckToWasteController);
	
	void visitMoveDiscardsToDeck(MoveDiscardsToDeckController moveDiscardsToDeckController);
	
	void visitMoveDiscardsToFoundation(MoveDiscardsToFoundationController moveDiscardsToFoundationController);
	
	void visitMoveDiscardsToBoardStair(MoveDiscardsToBoardStairController moveDiscardsToStairController);
	
	void visitMoveBoardStairToFoundation(MoveBoardStairToFoundationController moveBoardStairToFoundationController);
	
	void visitMoveBoarsStairToBoardStair(MoveBoardStairToBoardStairController moveBoardStairToBoardStairController);
	
	void visitFlipLastCardOfBoardStair(FlipLastCardOfBoardStairController flipLastCardOfBoardStair);
	
}
