package controller;

public interface ControllerVisitor {
	
	void visitMoveDeckToDiscardsController(MoveDeckToDiscardsController moveDeckToWasteController);
	
	void visitMoveDiscardsToDeckController(MoveDiscardsToDeckController moveDiscardsToDeckController);
	
	void visitMoveDiscardsToFoundationCotroller(MoveDiscardsToFoundationController moveDiscardsToFoundationController);
	
	void visitMoveDiscardsToBoardStairController(MoveDiscardsToBoardStairController moveDiscardsToStairController);
	
	void visitMoveBoarsStairToBoardStairController(MoveBoardStairToBoardStairController moveBoardStairToBoardStairController);
	
}
